name="MacGPG1"
appName=""

imgBackground="Installer/background_dmg.png"
volumeLayout="Installer/DS_Store"
rmName="Uninstall.app"

unset REVISION PRERELEASE
MAJOR=1
MINOR=4
REVISION=12-1

source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
